version: "3.9"

services:
  api:
    image: rgalicia0729/toolbox-challenge-api
    environment:
      PORT: 3000
    depends_on:
      - front
    ports:
      - "3000:3000"

  front: 
    image: rgalicia0729/toolbox-challenge-front
    ports:
      - "3001:3001"
